#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 490314-web-01 54.89.58.11:80 check
    server 490314-web-02 34.232.69.60:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
