#!/usr/bin/env bash
# install ufw and add configration
sudo apt install -y ufw
sudo service ufw start
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
