#!/usr/bin/env bash
#fix a web server to run Nginx as Nginx user lisetnign on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start   